# Generated by Django 4.2 on 2023-05-12 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Id_number", models.CharField(max_length=200)),
                ("patient_name", models.CharField(max_length=255)),
                ("gender", models.CharField(max_length=2)),
                ("permanent_address", models.CharField(max_length=255)),
                ("chitizenship_num", models.CharField(max_length=20)),
                ("father_name", models.CharField(max_length=255)),
                ("mother_name", models.CharField(max_length=255)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
