# Generated by Django 4.2 on 2023-05-17 02:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
        ("patientprofile", "0002_remove_patientinformation_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientStatus",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("is_available", models.BooleanField(default=False)),
                ("is_treated", models.BooleanField(default=False)),
                ("problem", models.CharField(max_length=400)),
            ],
        ),
        migrations.RenameField(
            model_name="patientinformation",
            old_name="Id_number",
            new_name="id_number",
        ),
    ]
