# Generated by Django 4.2 on 2023-05-17 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patientprofile", "0003_patientstatus_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientstatus",
            name="doctor",
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
