# Generated by Django 4.2 on 2023-05-17 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patientprofile", "0004_patientstatus_doctor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patientstatus",
            name="doctor",
            field=models.IntegerField(),
        ),
    ]
