# Generated by Django 4.2.1 on 2023-05-20 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('patientprofile', '0007_alter_patientreport_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientInformationDetail',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=255)),
                ('id_number', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('father_name', models.CharField(max_length=255)),
                ('mother_name', models.CharField(max_length=255)),
                ('citizenship_num', models.CharField(max_length=30)),
                ('blood_group', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('photo', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
